apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-agent
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: init
          # This is a small image with wait-for-it, choose whatever image
          # you prefer that waits for a service to be up. This image is built
          # from https://github.com/lqhl/wait-for-it
          image: gcr.io/spiffe-io/wait-for-it
          args: ["-t", "30", "127.0.0.1:7171"]
      containers:
        - name: spire-agent
          image: gcr.io/spiffe-io/spire-agent:1.0.0
          args: ["-config", "/run/spire/agent/agent.conf"]
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/agent/
              readOnly: false
            - name: spire-bundle
              mountPath: /run/spire/config/
              readOnly: false
            - name: spire-agent-socket
              mountPath: /run/spire/sockets/
              readOnly: false
      volumes:
        - name: spire-config
          configMap:
            name: spire-agent
        - name: spire-bundle
          hostPath:
            path: /run/spire/config/
            type: DirectoryOrCreate
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets/
            type: DirectoryOrCreate

